# Generated by Django 5.0.1 on 2024-04-17 09:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrondissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=128)),
                ('arrondissementChef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.arrondissement')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(default='', upload_to='front/src/lib/image/profil')),
                ('tel', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('arrondissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.arrondissement')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('numCni', models.CharField(blank=True, max_length=9)),
                ('photo', models.ImageField(upload_to='front/src/lib/image/photo')),
                ('declarationPerte', models.ImageField(blank=True, upload_to='front/src/lib/image/perte')),
                ('certificat', models.ImageField(upload_to='front/src/lib/image/certificat')),
                ('acteNaissance', models.ImageField(blank=True, upload_to='front/src/lib/image/acte')),
                ('typeDocument', models.CharField(choices=[('primata', 'primata'), ('duplicatatUse', 'duplicatatUse'), ('duplicatatPerte', 'duplicatatPerte')], default='primata', max_length=20)),
                ('etatDocument', models.CharField(choices=[('encours', 'encours'), ('refuser', 'refuser'), ('accepter', 'accepter')], default='encours', max_length=20)),
                ('dateDebut', models.DateField(default=datetime.datetime.now)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.utilisateur')),
            ],
        ),
    ]
