# Generated by Django 5.0.1 on 2024-04-29 11:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='', upload_to='front/src/lib/image/publication')),
                ('description', models.TextField(default='')),
                ('aimer', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=6)),
            ],
        ),
        migrations.RenameField(
            model_name='chef',
            old_name='identifiant',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='arrondissement',
            name='diriger',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], default='non', max_length=20),
        ),
        migrations.AddField(
            model_name='chef',
            name='numCni',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='chef',
            name='photo',
            field=models.ImageField(blank=True, upload_to='front/src/lib/image/chef'),
        ),
        migrations.AddField(
            model_name='chef',
            name='prenom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 29)),
        ),
        migrations.AddField(
            model_name='notification',
            name='lue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='utilisateur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.utilisateur'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_inscription',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 13, 34, 17, 623711)),
        ),
        migrations.AlterField(
            model_name='arrondissement',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenue', models.CharField(max_length=10000)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.utilisateur')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.publication')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liker', models.BooleanField(default=False)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.publication')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Rendezvou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fin', models.DateField(default=datetime.datetime.now)),
                ('heure', models.TimeField()),
                ('code', models.CharField(max_length=6)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.document')),
            ],
        ),
    ]
