# Generated by Django 5.0.1 on 2024-04-29 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_utilisateur_date_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvou',
            name='recuperer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_inscription',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 14, 28, 44, 475183)),
        ),
    ]
