# Generated by Django 5.0.1 on 2024-04-30 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_utilisateur_date_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='archiver',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 30)),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_inscription',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 14, 46, 9, 500576)),
        ),
    ]
