# Generated by Django 5.0.1 on 2024-05-01 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_document_archiver_alter_notification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lien',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 1)),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_inscription',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 16, 5, 40, 453895)),
        ),
    ]
