# Generated by Django 5.0.1 on 2024-05-08 16:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_notification_lien_alter_notification_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1000)),
                ('code', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1000)),
                ('code', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='arrondissement',
            name='description',
        ),
        migrations.AddField(
            model_name='arrondissement',
            name='code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 8)),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_inscription',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 18, 9, 12, 708459)),
        ),
        migrations.AddField(
            model_name='arrondissement',
            name='district',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.district'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.region'),
        ),
    ]
