# Generated by Django 5.0.1 on 2024-05-08 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_district_region_remove_arrondissement_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='date_inscription',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 18, 10, 28, 470075)),
        ),
    ]
