# Generated by Django 5.0.1 on 2024-05-10 10:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_utilisateur_date_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 10)),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_inscription',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 12, 11, 26, 983883)),
        ),
        migrations.CreateModel(
            name='Karatra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=14)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.document')),
            ],
        ),
    ]
