# Generated by Django 5.0.1 on 2024-05-15 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_karatra_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karatra',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 15, 14, 46, 18, 704769), null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_inscription',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 14, 46, 18, 682145)),
        ),
    ]
