# Generated by Django 5.0.1 on 2024-05-30 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_karatra_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sexe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='karatra',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 30, 5, 0, 8, 866465), null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 30)),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_inscription',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 5, 0, 8, 850461)),
        ),
    ]
